name: KAIST WSP Lab
description: KAIST Web Security & Privacy Lab
avatar: /images/logo-icon.svg
url: https://wsp-lab.github.io

main-images:
  - /images/main-photo_1.jpg
  - /images/main-photo_2.jpg
  - /images/main-photo_3.jpg

footer-links:
  dribbble:
  email: sl.son@kaist.ac.kr
  facebook:
  flickr:
  github: WSP-LAB
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

disqus:

google_analytics:

baseurl: ""
permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

people_prof:
  name: Sooel Son
  photo: /images/sooel.png
  homepage: https://sites.google.com/site/ssonkaist/home

people_phd:
  - name: Joongyum Kim
    photo:
    homepage:
  - name: Seongil Wi
    photo: /images/seongil.jpg
    homepage: https://seongil-wi.github.io/
  - name: Suyoung Lee
    photo:
    homepage: https://leeswimming.com/


people_master:
  - name: Sunnyeo Park
    photo:
    homepage:
  - name: Hyuntae Kim
    photo:
    homepage:
  - name: Hyunju Lee
    photo:
    homepage:
  - name: Daejun Kim ♔
    photo: /images/reset.png
    homepage: https://facebook.com/reset.test

people_intern:
  - name: Soyoung Lee
    photo:
    homepage:

people_researcher:
  - name: Sijae Woo
    photo:
    homepage:

people_alumni:
  - name: Taekjin Lee
    homepage:
    degree: Master
    work: National Security Research Institute, South Korea
  - name: Junghwan Park
    homepage: https://pagez.kr/
    degree: Master
    work: Naver, South Korea

publications:
  - year: 2020
    list:
    - title: "Montage: A Neural Network Language Model-Guided JavaScript Engine Fuzzer"
      link: https://leeswimming.com/papers/lee-sec20.pdf
      authors: Suyoung Lee, HyungSeok Han, Sang Kil Cha, and Sooel Son
      published: true
      booktitle: 20th USENIX Security Symposium (USENIX Security 2020)
      code: https://github.com/WSP-LAB/Montage
    - title: "FUSE: Finding File Upload Bugs via Penetration Testing"
      link: https://github.com/WSP-LAB/wsp-lab.github.io//papers/son-fuse-ndss20.pdf
      authors: Taekjin Lee, Seongil Wi (co-first author), Suyoung Lee, and Sooel Son
      published: true
      booktitle: 27th Network & Distributed System Security Symposium (NDSS 2020)
      code: https://github.com/WSP-LAB/FUSE
  - year: 2019
    list:
    - title: Who Spent My EOS? On the (In)Security of Resource Management of EOS.IO
      link: https://drive.google.com/file/d/1UzYFCnbYEFT2olpX7OwITxEqedtLthMm/view?usp=sharing
      authors: Sangsup Lee, Daejun Kim (co-first author), Dongkwan Kim, Sooel Son, and Yongdae Kim
      published: true
      booktitle: 13th USENIX Workshop on Offensive Technologies (WOOT 2019)
    - title: An Empirical Study of Prioritizing JavaScript Engine Crashes via Machine Learning
      link: https://drive.google.com/file/d/1rKlUkLMXmG1i0y9BqxFKf11lqeXVlyqJ/view
      authors: Sunnyeo Park, Dohyeok Kim, and Sooel Son
      published: true
      booktitle: 14th ACM ASIA Conference on Computer and Communications Security (ASIACCS 2019)
      code: https://github.com/WSP-LAB/CRScope
    - title: "Doppelgängers on the Dark Web: A Large-scale Assessment on Phishing Hidden Web Services"
      link: https://drive.google.com/file/d/15QpktkCeJcv1vKzW_K8I6KRYF7j1dZjV/view
      authors: Changhoon Yoon, Kwanwoo Kim, Yongdae Kim, Seungwon Shin, and Sooel Son
      published: true
      booktitle: "The Web Conference 2019: Security, Privacy, and Trust Research Track (WWW 2019) [oral presentation]"
    - title: "Hidden Figures: Comparative Latency Analysis of Cellular Networks with Fine-grained State Machine Models"
      link: https://drive.google.com/file/d/1PATYzbR2A5VAN_M6x-VwyQXizeQr4zyx/view
      authors: Sangwook Bae, Mincheol Son, Sooel Son, and Yongdae Kim
      booktitle: 20th International Workshop on Mobile Computing Systems and Applications (HOTMOBILE 2019)
      published: true
    - title: "Cybercriminal Minds: An Investigative Study of Cryptocurrency Abuses in the Dark Web"
      link: https://www.ndss-symposium.org/wp-content/uploads/2019/02/ndss2019_09-1_Lee_paper.pdf
      authors: Seunghyeon Lee, Changhoon Yoon, Heedo Kang, Yeonkeun Kim, Yongdae Kim, Dongsu Han, Sooel Son, and Seungwon Shin
      published: true
      booktitle: 26th Network & Distributed System Security Symposium (NDSS 2019)
  - year: 2018
    list:
    - title: "Pride and Prejudice in Progressive Web Apps: Abusing Native App-like Features in Web Applications"
      link: https://drive.google.com/file/d/1kDc4fnD4eZSuCCYqnw8ghGtm71p4Sq4w/view
      authors: Jiyeon Lee, Hayeon Kim, Junghwan Park, Insik Shin, and Sooel Son
      published: true
      booktitle: 25th ACM Conference on Computer and Communications Security (CCS 2018)
      code: https://github.com/spostman/ppp-ccs2018
      comments:
        - "There is an error in our paper in the proceedings: Safari 11.1 is NOT vulnerable to the history sniffing attack via cache."
  - year: "~ 2017"
    list:
    - title: What Mobile Ads Know About Mobile Users
      link: https://www.cs.cornell.edu/~shmat/shmat_ndss16.pdf
      authors: Sooel Son, Daehyeok Kim, and Vitaly Shmatikov
      published: true
      booktitle: 23rd Network & Distributed System Security Symposium (NDSS 2016)
      media: https://www.mediapost.com/publications/article/265783/mobile-ads-can-infer-users-medication-dating-pre.html
    - title: "Toward better server-side Web security"
      link: https://repositories.lib.utexas.edu/handle/2152/24821
      authors: Sooel Son
      published: true
      booktitle: UTCS Dissertation (2014)
    - title: "Diglossia: Detecting Code Injection Attacks with Precision and Efficiency"
      link: http://www.cs.utexas.edu/~shmat/shmat_ccs13.pdf
      authors: Sooel Son, Kathryn S McKinley, and Vitaly Shmatikov
      published: true
      booktitle: 20th ACM Conference on Computer and Communications Security (CCS 2013)
    - title: Model Checking Invariant Security Properties in OpenFlow
      link: http://www.csl.sri.com/users/vinod/papers/flover.pdf
      authors: Sooel Son, Seungwon Shin, Vinod Yegneswaran, Phil Porras, and Guofei Gu
      published: true
      booktitle: IEEE International Conference on Communications (ICC 2013)
    - title: "The Postman Always Rings Twice: Attacking and Defending postMessage in HTML5 Websites"
      link: http://www.cs.utexas.edu/~shmat/shmat_ndss13postman.pdf
      authors: Sooel Son and Vitaly Shmatikov
      published: true
      booktitle: 20th Network & Distributed System Security Symposium (NDSS 2013)
      comments: <b>Best student paper award</b>
    - title: "Fix Me Up: Repairing Access-Control Bugs in Web Applications"
      link: http://www.cs.utexas.edu/~shmat/shmat_ndss13fixmeup.pdf
      authors: Sooel Son, Kathryn S McKinley, and Vitaly Shmatikov
      published: true
      booktitle: 20th Network & Distributed System Security Symposium (NDSS 2013)
    - title: "RoleCast: Finding Missing Security Checks When You Do Not Know What Checks Are"
      link: http://www.cs.utexas.edu/~shmat/shmat_oopsla11.pdf
      authors: Sooel Son, Kathryn S McKinley, and Vitaly Shmatikov
      published: true
      booktitle: ACM SIGPLAN Conference on Object-Oriented Programming, Systems, Languages, and Applications (OOPSLA 2011)
    - title: "SAFERPHP: Finding Semantic Vulnerabilities in PHP Applications"
      link: http://www.cs.utexas.edu/~shmat/shmat_plas11.pdf
      authors: Sooel Son and Vitaly Shmatikov
      published: true
      booktitle: ACM SIGPLAN 6th Workshop on Programming Languages and Analysis for Security at PLDI 2011 (PLAS 2011)
    - title: "The Hitckhiker's Guide to DNS Cache Poisoning"
      link: http://www.cs.utexas.edu/~samuel/paper/dns-securecomm2010.pdf
      authors: Sooel Son and Vitaly Shmatikov
      published: true
      booktitle: 6th International ICST Conference on Security and Privacy in Communication Networks (SecureCOMM 2010)

teaching:
  - name: Machine Learning Application Trends in Information Security
    code: CS492
    link:
    semastors:
      - name: 2019 Fall
        link: https://spostman.github.io/cs492
  - name: Web Service Security and Privacy
    code: IS542
    link:
    semastors:
      - name: 2019 Spring
        link: https://docs.google.com/document/d/e/2PACX-1vQM71g1RWcrXYfdEzBvGGEY3jbBcUDOTdG3Y3e9f0s2_wRPXJbtc0ydO3bZ2pdTBrtB1Y87jB4ahJdL/pub
  - name: Web & Mobile Service Security
    code: IS593
    link: https://docs.google.com/document/d/1786AhpYOhtmrKgxZ0jbfg9UFLr3SXyqmoJDdWG_hyzs/preview?pli=1#
    semastors:
      - name: 2017 Fall
        link: https://docs.google.com/document/d/1786AhpYOhtmrKgxZ0jbfg9UFLr3SXyqmoJDdWG_hyzs/preview?pli=1
      - name: 2018 Spring
        link:
  - name: Machine Learning Application Trends in Information Security
    code: IS593
    link:
    semastors:
      - name: 2018 Fall
        link: https://docs.google.com/document/d/1oRNC_twHU3eEsNxfN-EyKpqWlSH_MaWfzF5Zuo1VRkg

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
