name: KAIST WSP Lab
description: KAIST Web Security & Privacy Lab
avatar: /images/logo-icon.svg
url: https://wsp-lab.github.io

main-images:
  - /images/main-photo_1.jpg
  - /images/main-photo_2.jpg
  - /images/main-photo_3.jpg

footer-links:
  dribbble:
  email: sl.son@kaist.ac.kr
  facebook:
  flickr:
  github: WSP-LAB
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

disqus:

google_analytics: UA-62491243-6

baseurl: ""
permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    
research:
  - subject: "R1. Analyzing security/privacy risks in Machine Learning (ML) models"
    list:
    - title: "Penetration Security Testing of ML Model Vulnerabilities and Defense  [IITP 전문연구실]"
      contents: We investigate various security and privacy threats in recent machine learning models and implement tools that assess the robustness of given ML models by conducting penetration security testing. 
      media: https://www.google.com/url?q=https%3A%2F%2Fgsis.kaist.ac.kr%2Fboard%2Fview%3Fbbs_id%3Dnews%26bbs_sn%3D1076%26page%3D1%26skey%3D%26svalue%3D%26menu%3D107&sa=D&sntz=1&usg=AFQjCNH3fSIxxKxg3cgm4ZUKTxYdpsK2kA

  - subject: "R2. Building tools for finding vulnerabilities in server/client-side web applications"
    list:
    - title: "[NDSS'21] The Abuser Inside Apps: Finding the Culprit Committing Mobile Ad Fraud"
      contents: The paper presents the design and implementation of FraudDetective, a dynamic testing frame- work that identifies ad fraud activities. FraudDetective computes a full stack trace from an observed ad fraud activity to a user event by connecting fragmented multiple stack traces, thus generating the causal relationships between user inputs and the observed fraudulent activity. We revised an Android Open Source Project (AOSP) to emit detected ad fraud activities along with their full stack traces, which help pinpoint the app modules responsible for the observed fraud activities. We evaluate FraudDetective on 48,172 apps from Google Play Store. FraudDetective reports that 74 apps are responsible for 34,453 ad fraud activities and find that 98.6% of the fraudulent behaviors originate from embedded third-party ad libraries.
      media: 
      photo: /images/Abuser.png
      paper: 
      code: 
      summary: 
    
    - title: "[USENIX Security'20] Montage: A Neural Network Language Model-Guided JavaScript Engine Fuzzer"
      contents: JavaScript (JS) engine vulnerabilities pose significant security threats affecting billions of web browsers. In this project, we present Montage, the first NNLM-guided fuzzer for finding JS engine vulnerabilities. The key aspect of our technique is to transform a JS abstract syntax tree (AST) into a sequence of AST subtrees that can directly train prevailing NNLMs. We demonstrate that Montage is capable of generating valid JS tests, and show that it outperforms previous studies in terms of finding vulnerabilities. Montage found 37 real-world bugs, including three CVEs, in the latest JS engines, demonstrating its efficacy in finding JS engine bugs.
      media: 
      photo: /images/Montage.png
      paper: /papers/lee-montage-sec20.pdf
      code: https://github.com/WSP-LAB/Montage
      summary: https://gsis.kaist.ac.kr/board/view?bbs_id=research&bbs_sn=1058&page=1&skey=&svalue=&menu=183
    
    - title: "[NDSS'20] FUSE: Finding File Upload Bugs via Penetration Testing"
      contents: An Unrestricted Executable File Upload (UEFU) vulnerability is a critical security threat that enables an adversary to upload her choice of a forged file to a target web server and e to conduct remote code execution of this  uploaded file via triggering its URL. We design and implement FUSE, a penetration testing tool designed to discover UFU and UEFU vulnerabilities in server-side PHP web applications. The goal of FUSE is to generate upload requests; each request becomes an exploit payload that triggers a UFU or UEFU vulnerability. FUSE discovered 30 previously unreported UEFU vulnerabilities, including 15 CVEs from 33 real-world web applications, thereby demonstrating its efficacy in finding code execution bugs via file uploads. 
      media: https://www.zdnet.com/article/academics-find-30-file-upload-vulnerabilities-in-23-web-apps-cmses-and-forums/
      photo: /images/FUSE.png
      paper: /papers/lee-fuse-ndss20.pdf
      code: https://github.com/WSP-LAB/FUSE
      summary: https://gsis.kaist.ac.kr/board/view?bbs_id=research&bbs_sn=1045&page=1&skey=&svalue=&menu=183
   
  - subject: "R3. Finding security/privacy vulnerabilities in web services"
    list:
    - title: "[USENIX WOOT'19] Who Spent My EOS? On the (In)Security of Resource Management of EOS.IO"
      contents: We investigate the design architecture of EOS.IO. Based on this investigation, we introduce four attacks whose root causes stem from the unique characteristics of EOS.IO, including intentionally slowing down the block creation time—which can disrupt the essential functions of its blockchain and incapacitate the entire EOS.IO system. We  also find that an adversary can partially freeze the execution of a target smart contract or maliciously consume all the resources of a target user with crafted requests. We report all the identified threats to the EOS.IO foundation, one of which is confirmed to be fatal. Finally, we discuss possible mitigations against the proposed attacks. 
      media: 
      photo: /images/EOS.png
      paper: /papers/lee-eos-woot19.pdf
      code: 
      summary: 

    - title: "[CCS'18] Pride and Prejudice in Progressive Web Apps: Abusing Native App-like Features in Web Applications"
      contents: Progressive Web App (PWA) is a new generation of Web application designed to provide native app-like browsing experiences even when a browser is offline. We conduct the first systematic study of the security and privacy aspects unique to PWAs. We identify security flaws in main browsers as well as design flaws in popular third-party push services, that exacerbate the phishing risk. We introduce a new side-channel attack that infers the victim’s history of visited PWAs. The proposed attack exploits the offline browsing feature of PWAs using a cache. We demonstrate a cryptocurrency mining attack which abuses service workers. Defenses and recommendations to mitigate the identified security and privacy risks are suggested with in-depth understanding. 
      media: 
      photo: /images/PPP.png
      paper: /papers/son-ppp-ccs18.pdf
      code: https://github.com/spostman/ppp-ccs2018
      summary: 

  - subject: "R4. Analyzing online scam/criminal activities  occurring on the Internet"
    list:
    - title: "[WWW'19] Doppelgängers on the Dark Web: A Large-scale Assessment on Phishing Hidden Web Services"
      contents: We conducted an in-depth measurement study to demystify the prevalent phishing websites on the Dark Web. We analyzed the text content of 28,928 HTTP Tor hidden services hosting 21 million dark webpages and confirmed 901 phishing domains. We also discovered a trend on the Dark Web in which service providers perceive dark web domains as their service brands. This trend exacerbates the risk of phishing for their service users who remember only a partial Tor hidden service address. Our work facilitates a better understanding of the phishing risks on the Dark Web and encourages further research on establishing an authentic and reliable service on the Dark Web. 
      media: 
      photo: /images/Doppelgängers.png
      paper: /papers/yoon-www19.pdf
      code: 
      summary: https://cs.kaist.ac.kr/board/view?bbs_id=news&bbs_sn=8793&page=1&skey=subject&svalue=%EC%86%90%EC%88%98%EC%97%98&menu=83
    

people_prof:
  name: Sooel Son
  photo: /images/sooel.png
  homepage: https://sites.google.com/site/ssonkaist/home

people_phd:
  - name: Joongyum Kim
    photo: /images/joongyum.jpg
    homepage:
  - name: Seongil Wi
    photo: /images/seongil.jpg
    homepage: https://seongil-wi.github.io/
  - name: Suyoung Lee
    photo: /images/swimming.png
    homepage: https://leeswimming.com/
  - name: Sunnyeo Park
    photo: /images/sunnyeo.jpg
    homepage:

people_master:
  - name: Soyoung Lee
    photo: /images/soyoung.jpg
    homepage:
  - name: Dahun Lee
    photo: /images/dahun.jpg
    homepage:
  - name: Wonho Song
    photo: /images/wonho.jpg
    homepage:

people_researcher:
  - name: Sijae Woo
    photo:
    homepage:

people_alumni:
  - name: Taekjin Lee
    homepage:
    degree: Master
    work: National Security Research Institute, South Korea
  - name: Junghwan Park
    homepage: https://pagez.kr/
    degree: Master
    work: Naver, South Korea
  - name: Daejun Kim
    homepage: https://facebook.com/reset.test
    degree: Master
    work: Theori, South Korea
  - name: Hyuntae Kim
    homepage:
    degree: Master
    work:
  - name: Hyunjoo Lee
    homepage:
    degree: Master
    work: Korea Institute of Nuclear Nonproliferation And Control, South Korea

news:
  list:
  - date: Feb, 2021
    comments: A paper accepted in ASIACCS'21!
  - date: Dec, 2020
    comments: A paper accepted in <strong>USENIX Security'21</strong>!

publications:
  - year: 2021
    list:
    - title: "Security Analysis on Practices of Certificate Authorities in the HTTPS Phishing Ecosystem"
      authors: Doowon Kim, Haehyun Cho, Yonghwi Kwon, Adam Oest, Adam Doupe, Sooel Son, Gail-Joon Ahn, and Tudor Dumitras
      published: false
      booktitle: 16th ACM ASIA Conference on Computer and Communications Security (ASIACCS 2021)
    - title: "AdCube: WebVR Ad Fraud and Practical Confinement of Third-Party Ads"
      authors: Hyunjoo Lee, Jiyeon Lee (co-leading author), Daejun Kim, Suman Jana, Insik Shin, and Sooel Son
      published: false
      toptier_security: true
      booktitle: 21st USENIX Security Symposium (USENIX Security 2021)
    - title: "The Abuser Inside Apps: Finding the Culprit Committing Mobile Ad Fraud"
      link: https://wsp-lab.github.io/papers/kim-fraud_detective-ndss21.pdf
      authors: Joongyum Kim, Junghwan Park (co-leading author), and Sooel Son
      toptier_security: true
      published: true
      booktitle: 28th Network & Distributed System Security Symposium (NDSS 2021)
  - year: 2020
    list:
    - title: "Lumos: Improving Smart Home IoT Visibility and Interoperability Through Analyzing Mobile Apps"
      link: https://wsp-lab.github.io/papers/kim-lumos-icnp20.pdf
      authors: Jeongmin Kim, Steven Y. Ko, Sooel Son, and Dongsu Han
      published: true
      booktitle: 28th IEEE International Conference on Network Protocols (ICNP 2020)
    - title: "Montage: A Neural Network Language Model-Guided JavaScript Engine Fuzzer"
      link: https://wsp-lab.github.io/papers/lee-montage-sec20.pdf
      authors: Suyoung Lee, HyungSeok Han, Sang Kil Cha, and Sooel Son
      toptier_security: true      
      published: true
      booktitle: 20th USENIX Security Symposium (USENIX Security 2020)
      code: https://github.com/WSP-LAB/Montage
    - title: "FUSE: Finding File Upload Bugs via Penetration Testing"
      link: https://wsp-lab.github.io/papers/lee-fuse-ndss20.pdf
      authors: Taekjin Lee, Seongil Wi (co-leading author), Suyoung Lee, and Sooel Son
      toptier_security: true
      published: true
      booktitle: 27th Network & Distributed System Security Symposium (NDSS 2020)
      code: https://github.com/WSP-LAB/FUSE
  - year: 2019
    list:
    - title: Who Spent My EOS? On the (In)Security of Resource Management of EOS.IO
      link: https://wsp-lab.github.io/papers/lee-eos-woot19.pdf
      authors: Sangsup Lee, Daejun Kim (co-leading author), Dongkwan Kim, Sooel Son, and Yongdae Kim
      published: true
      booktitle: 13th USENIX Workshop on Offensive Technologies (WOOT 2019)
    - title: An Empirical Study of Prioritizing JavaScript Engine Crashes via Machine Learning
      link: https://wsp-lab.github.io/papers/park-crscope-asiaccs19.pdf
      authors: Sunnyeo Park, Dohyeok Kim, and Sooel Son
      published: true
      booktitle: 14th ACM ASIA Conference on Computer and Communications Security (ASIACCS 2019)
      code: https://github.com/WSP-LAB/CRScope
    - title: "Doppelgängers on the Dark Web: A Large-scale Assessment on Phishing Hidden Web Services"
      link: https://wsp-lab.github.io/papers/yoon-www19.pdf
      authors: Changhoon Yoon, Kwanwoo Kim, Yongdae Kim, Seungwon Shin, and Sooel Son
      toptier_cs: true
      published: true
      booktitle: "The Web Conference 2019: Security, Privacy, and Trust Research Track (WWW 2019)"
    - title: "Hidden Figures: Comparative Latency Analysis of Cellular Networks with Fine-grained State Machine Models"
      link: https://wsp-lab.github.io/papers/bae-hiddenfigure-hotmobile19.pdf
      authors: Sangwook Bae, Mincheol Son, Sooel Son, and Yongdae Kim
      booktitle: 20th International Workshop on Mobile Computing Systems and Applications (HOTMOBILE 2019)
      published: true
    - title: "Cybercriminal Minds: An Investigative Study of Cryptocurrency Abuses in the Dark Web"
      link: https://wsp-lab.github.io/papers/lee-mfscope-ndss19.pdf
      authors: Seunghyeon Lee, Changhoon Yoon, Heedo Kang, Yeonkeun Kim, Yongdae Kim, Dongsu Han, Sooel Son, and Seungwon Shin
      toptier_security: true
      published: true
      booktitle: 26th Network & Distributed System Security Symposium (NDSS 2019)
  - year: 2018
    list:
    - title: "Pride and Prejudice in Progressive Web Apps: Abusing Native App-like Features in Web Applications"
      link: https://wsp-lab.github.io/papers/son-ppp-ccs18.pdf
      authors: Jiyeon Lee, Hayeon Kim, Junghwan Park, Insik Shin, and Sooel Son
      published: true
      toptier_security: true
      booktitle: 25th ACM Conference on Computer and Communications Security (CCS 2018)
      code: https://github.com/spostman/ppp-ccs2018
      comments:
        - "There is an error in our paper in the proceedings: Safari 11.1 is NOT vulnerable to the history sniffing attack via cache."
  - year: "~ 2017"
    list:
    - title: What Mobile Ads Know About Mobile Users
      link: https://www.cs.cornell.edu/~shmat/shmat_ndss16.pdf
      authors: Sooel Son, Daehyeok Kim, and Vitaly Shmatikov
      published: true
      toptier_security: true
      booktitle: 23rd Network & Distributed System Security Symposium (NDSS 2016)
      media: https://www.mediapost.com/publications/article/265783/mobile-ads-can-infer-users-medication-dating-pre.html
    - title: "Toward better server-side Web security"
      link: https://repositories.lib.utexas.edu/handle/2152/24821
      authors: Sooel Son
      published: true
      booktitle: UTCS Dissertation (2014)
    - title: "Diglossia: Detecting Code Injection Attacks with Precision and Efficiency"
      link: http://www.cs.utexas.edu/~shmat/shmat_ccs13.pdf
      authors: Sooel Son, Kathryn S McKinley, and Vitaly Shmatikov
      toptier_security: true
      published: true
      booktitle: 20th ACM Conference on Computer and Communications Security (CCS 2013)
    - title: Model Checking Invariant Security Properties in OpenFlow
      link: http://www.csl.sri.com/users/vinod/papers/flover.pdf
      authors: Sooel Son, Seungwon Shin, Vinod Yegneswaran, Phil Porras, and Guofei Gu
      published: true
      booktitle: IEEE International Conference on Communications (ICC 2013)
    - title: "The Postman Always Rings Twice: Attacking and Defending postMessage in HTML5 Websites"
      link: http://www.cs.utexas.edu/~shmat/shmat_ndss13postman.pdf
      authors: Sooel Son and Vitaly Shmatikov
      published: true
      toptier_security: true
      booktitle: 20th Network & Distributed System Security Symposium (NDSS 2013)
      comments: <b>Best student paper award</b>
    - title: "Fix Me Up: Repairing Access-Control Bugs in Web Applications"
      link: http://www.cs.utexas.edu/~shmat/shmat_ndss13fixmeup.pdf
      authors: Sooel Son, Kathryn S McKinley, and Vitaly Shmatikov
      toptier_security: true
      published: true
      booktitle: 20th Network & Distributed System Security Symposium (NDSS 2013)
    - title: "RoleCast: Finding Missing Security Checks When You Do Not Know What Checks Are"
      link: http://www.cs.utexas.edu/~shmat/shmat_oopsla11.pdf
      authors: Sooel Son, Kathryn S McKinley, and Vitaly Shmatikov
      toptier_cs: true
      published: true
      booktitle: ACM SIGPLAN Conference on Object-Oriented Programming, Systems, Languages, and Applications (OOPSLA 2011)
    - title: "SAFERPHP: Finding Semantic Vulnerabilities in PHP Applications"
      link: http://www.cs.utexas.edu/~shmat/shmat_plas11.pdf
      authors: Sooel Son and Vitaly Shmatikov
      published: true
      booktitle: ACM SIGPLAN 6th Workshop on Programming Languages and Analysis for Security at PLDI 2011 (PLAS 2011)
    - title: "The Hitckhiker's Guide to DNS Cache Poisoning"
      link: http://www.cs.utexas.edu/~samuel/paper/dns-securecomm2010.pdf
      authors: Sooel Son and Vitaly Shmatikov
      published: true
      booktitle: 6th International ICST Conference on Security and Privacy in Communication Networks (SecureCOMM 2010)

teaching:
  - name: Machine Learning Application Trends in Information Security
    code: CS492
    link:
    semastors:
      - name: 2019 Fall
        link: https://spostman.github.io/cs492
  - name: Web Service Security and Privacy
    code: IS542
    link:
    semastors:
      - name: 2019 Spring
        link: https://docs.google.com/document/d/e/2PACX-1vQM71g1RWcrXYfdEzBvGGEY3jbBcUDOTdG3Y3e9f0s2_wRPXJbtc0ydO3bZ2pdTBrtB1Y87jB4ahJdL/pub
  - name: Web & Mobile Service Security
    code: IS593
    link: https://docs.google.com/document/d/1786AhpYOhtmrKgxZ0jbfg9UFLr3SXyqmoJDdWG_hyzs/preview?pli=1#
    semastors:
      - name: 2017 Fall
        link: https://docs.google.com/document/d/1786AhpYOhtmrKgxZ0jbfg9UFLr3SXyqmoJDdWG_hyzs/preview?pli=1
      - name: 2018 Spring
        link:
  - name: Machine Learning Application Trends in Information Security
    code: IS593
    link:
    semastors:
      - name: 2018 Fall
        link: https://docs.google.com/document/d/1oRNC_twHU3eEsNxfN-EyKpqWlSH_MaWfzF5Zuo1VRkg

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
